ktor:
  application:
    modules:
      - dev.pinta.lounge.ApplicationKt.module
  deployment:
    port: 8080
lounge:
  name: "lounge"
  security:
    secret: $JWT_SECRET
postgres:
  url: $DB_URL
  user: $DB_USER
  password: $DB_PSW